pipeline:  
  docker_latest:
    image: docker:latest
    volumes:
      - /root/.docker:/root/.docker
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - cd ./Nailhang.Blazor/docker
      - docker build -t $$DOCKER_REGISTRY/nailhangblazor:latest .
      - docker push $$DOCKER_REGISTRY/nailhangblazor:latest
    secrets: [ docker_registry ]
    when:
      event: [push]
      branch: [master]
  docker_release:
    image: docker:latest
    volumes:
      - /root/.docker:/root/.docker
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo ${DRONE_TAG##v}
      - cd ./Nailhang.Blazor/docker
      - docker build -t $$DOCKER_REGISTRY/nailhangblazor:$$DRONE_TAG .
      - docker push $$DOCKER_REGISTRY/nailhangblazor:$$DRONE_TAG
    secrets: [ docker_registry ]
    when:
      event: tag
      branch: [master]