pipeline:  
  blazor_build_check:
    image: mcr.microsoft.com/dotnet/core/sdk:3.0
    volumes:
      - /root/.docker:/root/.docker
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - cd ./Nailhang.Blazor
    - dotnet build
    when:
      event: [push, tag]
  docker_latest:
    image: docker:latest
    volumes:
      - /root/.docker:/root/.docker
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - cd ./Nailhang.Blazor/docker
      - docker build -t $$DOCKER_REGISTRY/nailhangblazor:latest .
      - docker push $$DOCKER_REGISTRY/nailhangblazor:latest
    secrets: [ docker_registry ]
    when:
      event: [push]
  docker_release:
    image: docker:latest
    volumes:
      - /root/.docker:/root/.docker
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo ${DRONE_TAG##v}
      - cd ./Nailhang.Blazor/docker
      - docker build -t $$DOCKER_REGISTRY/nailhangblazor:$$DRONE_TAG .
      - docker push $$DOCKER_REGISTRY/nailhangblazor:$$DRONE_TAG
    secrets: [ docker_registry ]
    when:
      event: tag